# Generated by Django 4.1 on 2022-11-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_answer_name_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='clik_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
