# Generated by Django 4.1 on 2022-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0004_alter_question_clik_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='su_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
