# Generated by Django 4.1 on 2022-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0005_question_su_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='con_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
