# Generated by Django 4.1 on 2022-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0006_question_con_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='an_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
